version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"  # Expose to internet and other containers
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - qvickly_network
      - default  # Use default network for system-wide access

  redis:
    image: redis:latest
    container_name: redis_cache
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Expose to internet and other containers
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - qvickly_network
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qvickly_app
    ports:
      - "8080:8080"  # Direct access to Go app
    environment:
      - host=postgres
      - port=5432
      - user=postgres
      - password=postgres
      - dbname=quickkart
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GO_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - qvickly_network
      - default

  nginx:
    image: nginx:alpine
    container_name: qvickly_nginx
    ports:
      - "80:80"     # HTTP access
      - "443:443"   # HTTPS access
      - "8090:8090" # Alternative port for direct nginx access
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - qvickly_network
      - default

  backup:
    image: postgres:latest
    depends_on:
      - postgres
    volumes:
      - postgres_data:/src/data
      - postgres_backup:/backup
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quickkart
    command: |
      bash -c 'while true; do
        pg_dump -h postgres -U postgres postgres > /backup/backup_$$(date +%Y%m%d_%H%M%S).sql;
        sleep 86400;
      done'
    networks:
      - qvickly_network

volumes:
  postgres_data:
  postgres_backup:
  redis_data:

# Define networks for maximum connectivity
networks:
  qvickly_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: qvickly_bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          